#!/usr/bin/env python3
"""
generate_dictionary.py — Convert translation-map.json into dictionary.txt
for the True Blue English patch hook DLL.

The dictionary file uses tab-separated Shift-JIS encoded lines:
    {Japanese text}\t{English text}

The hook DLL loads this at runtime and replaces matching Japanese text
with the English translation.

Usage:
    python generate_dictionary.py
    (reads ../translation-map.json, writes dictionary.txt)
"""

import json
import os
import sys


def wrap_text(text: str, max_width: int = 38) -> str:
    """
    Word-wrap English text to fit the game's text box.
    640x480 resolution with ~24px font ≈ 38 chars per line.
    """
    if len(text) <= max_width:
        return text

    lines = []
    for paragraph in text.split('\n'):
        words = paragraph.split(' ')
        current_line = ''
        for word in words:
            if not current_line:
                current_line = word
            elif len(current_line) + 1 + len(word) <= max_width:
                current_line += ' ' + word
            else:
                lines.append(current_line)
                current_line = word
        if current_line:
            lines.append(current_line)

    return '\n'.join(lines)


def main():
    map_path = os.path.join(os.path.dirname(__file__), '..', 'translation-map.json')
    out_path = os.path.join(os.path.dirname(__file__), 'dictionary.txt')

    print(f'Reading {map_path}...')
    with open(map_path, 'r', encoding='utf-8') as f:
        tmap = json.load(f)

    print(f'  {len(tmap)} entries in translation map')

    count = 0
    skipped = 0
    with open(out_path, 'w', encoding='shift-jis', errors='replace') as out:
        out.write('# True Blue English Patch Dictionary\n')
        out.write('# Format: {Japanese}\\t{English}\n')
        out.write('# Generated by generate_dictionary.py\n\n')

        for jp, en in tmap.items():
            if not jp or not en:
                skipped += 1
                continue

            # Skip meta-lines (choice labels, file headers)
            if jp.startswith('[選択肢') or jp.startswith('  '):
                skipped += 1
                continue
            if jp.startswith('-----') or jp.startswith('*****'):
                skipped += 1
                continue

            # The game sends text with leading ideographic space (U+3000)
            # and character names in brackets. Keep the JP key as-is
            # for exact matching.
            jp_clean = jp
            en_clean = wrap_text(en.strip())

            # Try encoding both sides as Shift-JIS
            try:
                jp_clean.encode('shift-jis')
                en_clean.encode('shift-jis')
            except UnicodeEncodeError:
                skipped += 1
                continue

            out.write(f'{jp_clean}\t{en_clean}\n')
            count += 1

    print(f'  Wrote {count} entries to {out_path}')
    print(f'  Skipped {skipped} entries (meta-lines or encoding issues)')
    print(f'\nDone! Copy dictionary.txt to the game folder.')


if __name__ == '__main__':
    main()
